resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr
  - name: pull-request-test
    type: docker-image
    source:
      repository: jtarchie/pr
      tag: test

resources:
  - name: git-pr
    type: git
    source:
      uri: git@github.com:jtarchie/pullrequest-resource
      branch: master
      private_key: {{github-private-key}}
  - name: docker-pr
    type: docker-image
    source:
      username: {{docker-username}}
      password: {{docker-password}}
      repository: jtarchie/pr
  - name: git-pull-requests
    type: pull-request
    source:
      access_token: {{github-access-token}}
      every: true
      private_key: {{github-private-key}}
      repo: jtarchie/pullrequest-resource
  - name: merge-pull-requests
    type: pull-request-test
    source:
      access_token: {{github-access-token}}
      every: true
      private_key: {{github-private-key}}
      base: test-merge
      repo: jtarchie/pullrequest-resource

jobs:
  - name: test-pr-merge
    plan:
      - get: merge-pull-requests
      - put: merge-pull-requests
        params:
          path: merge-pull-requests
          status: success
          merge:
            method: merge
            commit_msg: merge-pull-requests/README.md
  - name: pr tests
    plan:
      - get: git-pull-requests
        trigger: true
        version: every
      - task: rspec
        privileged: true
        config:
          image_resource:
            type: docker-image
            source:
              repository: jtarchie/pr
              tag: test
          inputs:
            - name: git-pull-requests
          platform: linux
          run:
            path: sh
            args: ['-c', 'cd git-pull-requests && bundle install && bundle exec rspec']
        on_success:
          put: git-pull-requests
          params:
            path: git-pull-requests
            status: success
        on_failure:
          put: git-pull-requests
          params:
            path: git-pull-requests
            status: failure
  - name: docker
    plan:
      - get: git-pr
        trigger: true
      - task: tag
        config:
          image_resource:
            type: docker-image
            source:
              repository: alpine
          platform: linux
          outputs:
            - name: tag
          run:
            path: sh
            args: ["-c", "echo test > tag/name"]
      - put: docker-pr
        params:
          build: git-pr
          dockerfile: git-pr/Dockerfile.test
          tag: tag/name
          get_params:
            skip_download: true
  - name: tests
    plan:
      - get: git-pr
        passed: [ docker ]
        trigger: true
      - task: rspec
        privileged: true
        config:
          image_resource:
            type: docker-image
            source:
              repository: jtarchie/pr
              tag: test
          inputs:
            - name: git-pr
          platform: linux
          run:
            path: sh
            args: ['-c', 'cd git-pr && bundle install && bundle exec rspec']
  - name: release
    plan:
      - get: git-pr
        passed: [ tests ]
      - task: next-tag
        config:
          image: /var/vcap/packages/git_resource/rootfs
          platform: linux
          inputs:
            - name: git-pr
          outputs:
            - name: tag
          run:
            path: bash
            args:
              - -c
              - |
                set -eux
                echo v > tag/prefix
                pushd git-pr
                  git tag -l | sed -e "s/v//" | sort -n | tail -n 1 | xargs -n 1 expr 1 + > ../tag/name
                popd
      - put: docker-pr
        params:
          build: git-pr
          dockerfile: git-pr/Dockerfile
          tag: tag/name
          tag_prefix: v
          tag_as_latest: true
          get_params:
            skip_download: true
      - put: git-pr
        params:
          repository: git-pr
          only_tag: true
          tag: tag/name
          tag_prefix: v
