#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp $TMPDIR/pullrequest-resource.XXXXXX)
cat > $payload <&0

$(dirname $0)/lib/commands/check.rb $1 >&3 < $payload
