#!/usr/bin/env ruby

require 'json'
require 'octokit'
require_relative 'common'

def input
  @input ||= JSON.parse(ARGF.read).tap do |input|
    input['version'] ||= {}
  end
end

def json!(payload)
  puts JSON.generate(payload)
  exit
end

load_key input

repo = Repository.new(name: input['source']['repo'])

next_pull_request = repo.next_pull_request(id: input['version']['pr'], sha: input['version']['ref'])
if next_pull_request
  json!([next_pull_request.as_json])
else
  json!([])
end
