#!/usr/bin/env ruby

require 'json'
require 'octokit'
require_relative 'common'

destination = ARGV.shift

def input
  @input ||= JSON.parse(ARGF.read).tap do |input|
    input['version'] ||= {}
    input['params'] ||= {}
  end
end

def uri
  input['source']['uri'] || "https://github.com/#{input['source']['repo']}"
end

def ref
  input['version']['ref']
end

load_key input

pr = Octokit.pull_request(input['source']['repo'], input['version']['pr'])

system("git clone --depth 1 #{uri} #{destination} 1>&2")
Dir.chdir(destination) do
  system("git fetch -q origin pull/#{pr['id']}/head:pr-#{pr['id']}")
  system("git checkout pr-#{pr['id']}")
  system("git config --add pullrequest.url #{pr['url']}")
end

puts JSON.generate(version:  { ref: ref, pr: pr['id'] },
                   metadata: { url: pr['url'] })
