#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

. $(dirname $0)/common.sh

payload=$(mktemp $TMPDIR/pullrequest-resource.XXXXXX)
cat > $payload <&0
load_pubkey $payload
configure_git_ssl_verification $payload
configure_credentials $payload

git_config_payload=$(jq -r '.source.git_config // []' < $payload)
configure_git_global "${git_config_payload}"

$(dirname $0)/lib/commands/out.rb $1 >&3 < $payload
